lms:main.o bookManagement.o userLoginAndRegister.o
	gcc main.o bookManagement.o userLoginAndRegister.o -o lms
	
main.o:main.c
	gcc -c main.c -o main.o

bookManagement.o:bookManagement.c 
	gcc -c bookManagement.c -o bookManagement.o

userLoginAndRegister.o:userLoginAndRegister.c 
	gcc -c userLoginAndRegister.c -o userLoginAndRegister.o
clear: